import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('test004@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('test00@');
  await page.getByRole('textbox', { name: 'Password' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Password' }).fill('test00@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Search Trips' }).click();
  await page.locator('div').filter({ hasText: /^₹60013 seats leftSelect Seats$/  }).getByRole('button').click();
  await page.getByText('39').click();
  await page.getByText('40').click();
  await page.getByRole('button', { name: 'Book Seats' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByText('39', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^40$/ }).click();
  await page.getByText('39').click();
  await page.getByRole('button', { name: 'Book Seats' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'View My Bookings' }).click();
  await page.getByRole('button', { name: 'Find Buses' }).click();
  await page.getByRole('button', { name: 'Search Trips' }).click();
  await page.locator('div').filter({ hasText: /^₹60012 seats leftSelect Seats$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'My Bookings' }).click();
  await page.getByText('Trip ID: d10c89ca').click();
  await page.getByTestId('toggle-cancel-options').click();
  await page.getByTestId('seat-button-39').click();
  await page.getByTestId('confirm-cancellation').click();
  await page.getByTestId('alert-message').click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('test001@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'My Bookings' }).click();
});